baseURL: "https://adityatelange.github.io/"
title: "@abiydv"
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Posts
          url: /posts/
          weight: 5
        - name: About
          url: /about/
          weight: 10


params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod
  # author: ["Me", "You"] # multiple authors
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  # images: ""
  # assets:
  #   favicon: '<path / external url>'

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hello \U0001F44B"
    Content: >
      I'm Abhinav, a DevOps and Cloud professional with a keen interest in Cloud Security, Automation, GitOps etc.
      Always up for a new challenge!

  socialIcons:
    - name: email
      url: "#"
    - name: linkedin
      url: "#"
    - name: github
      url: "https://github.com/abiydv"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
